######################################################################
#
# Configuration steps on the FlashBlade to prepare for the PoC
#
# Assumptions:
#   1. Ansible user is root, and "become" needed for other users. First
#      need to enable root access with "sudo vi /root/.ssh/authorized_keys"
#      if needed (e.g., on Outposts).
#
######################################################################
---
### Set up the FlashBlade to be ready for the deployment
### Save the access credentials in files for later
### Run all the FlashBlade tasks locally
- name: Install or upgrade required purity-fb Python module
  pip:
    name: purity_fb
    state: present
    virtualenv: "{{ lookup('env','VIRTUAL_ENV') }}"

- name: Install or upgrade required py-pure-client Python module
  pip:
    name: py-pure-client
    state: present
    virtualenv: "{{ lookup('env','VIRTUAL_ENV') }}"

- name: Collect FlashBlade configuration info
  purefb_info:
    gather_subset:
      - config
    fb_url: "{{ fb_mgmt }}"
    api_token: "{{ fb_api_token }}"
  ignore_errors: yes
  # Ignore errors just in case. Usually due to self-signed TLS certificates
  register: blade_info
- name: Show FlashBlade configuration information
  debug:
    msg:
      - "{{ blade_info['purefb_info']['config'] }}"

- name: Collect Bucket info
  purefb_info:
    gather_subset:
      - buckets
    fb_url: "{{ fb_mgmt }}"
    api_token: "{{ fb_api_token }}"
  ignore_errors: yes
  # Ignore errors just in case. Usually due to self-signed TLS certificates
  register: blade_info
- name: Show information on existing FlashBlade buckets
  debug:
    msg:
      - "{{ blade_info['purefb_info']['buckets'] }}"

- name: Create new Filesystem to use for PoC
  purefb_fs:
    name: "{{ fb_fs_name }}"
    size: "{{ fb_fs_size }}"
    snapshot: true
    fastremove: true
    nfsv4: false
    state: present
    fb_url: "{{ fb_mgmt }}"
    api_token: "{{ fb_api_token }}"

- name: Create new S3 Account to use for PoC
  purefb_s3acc:
    name: "{{ fb_s3_acct }}"
    state: present
    fb_url: "{{ fb_mgmt }}"
    api_token: "{{ fb_api_token }}"

- name: Create new S3 User to use for PoC and record credentials
  purefb_s3user:
    name: "{{ fb_s3_user }}"
    account: "{{ fb_s3_acct }}"
    access_key: yes
    state: present
    fb_url: "{{ fb_mgmt }}"
    api_token: "{{ fb_api_token }}"
  register: result
- debug: var=result

- name: Clean up any old configuration files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ aws_config_path }}"
    - "{{ auth_config_path }}"

- name: Save credentials in AWS Config file
  blockinfile:
    path: "{{ aws_config_path }}"
    backup: yes
    create: yes
    mode: '0600'
    marker: "### {mark} FlashBlade S3 Credestials for Account = {{ fb_s3_acct }}/{{ fb_s3_user }}"
    block: |
      [default]
      aws_access_key_id = {{ result['s3user_info']['fb_s3user']['access_id'] }}
      aws_secret_access_key = {{ result['s3user_info']['fb_s3user']['access_key'] }}

- name: Save credentials in auth_params file
  blockinfile:
    path: "{{ auth_config_path }}"
    backup: yes
    create: yes
    mode: '0600'
    marker: ''
    block: |
      awsenablehttps = 0
      awsauth = {{ result['s3user_info']['fb_s3user']['access_id'] }}:{{ result['s3user_info']['fb_s3user']['access_key'] }}
      awsendpoint = {{ fb_data }}

- name: Create new S3 Bucket to use for PoC
  purefb_bucket:
    name: "{{ fb_s3_bucket }}"
    account: "{{ fb_s3_acct }}"
    state: present
    versioning: absent
    fb_url: "{{ fb_mgmt }}"
    api_token: "{{ fb_api_token }}"
  when: fb_s3_bucket not in blade_info['purefb_info']['buckets']

- pause:
    prompt: |
      Check that the last step was successful.
      If everying looks good, hit Ctrl-C,C
  when: check_exec

...
